### Data-5

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
data_5 = pd.read_csv('../DataSet/Screening/Screening question/Autism_Data.arff')
data_5

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,'United States',no,6,'18 and more',Self,NO
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5,'18 and more',Self,NO
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8,'18 and more',Parent,YES
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,'United States',no,6,'18 and more',Self,NO
4,1,0,0,0,0,0,0,1,0,0,...,f,?,no,no,Egypt,no,2,'18 and more',?,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,f,White-European,no,no,Russia,no,7,'18 and more',Self,YES
700,1,0,0,0,0,0,0,1,0,1,...,m,Hispanic,no,no,Mexico,no,3,'18 and more',Parent,NO
701,1,0,1,1,1,0,1,1,0,1,...,f,?,no,no,Russia,no,7,'18 and more',?,YES
702,1,0,0,1,1,0,1,0,1,1,...,m,'South Asian',no,no,Pakistan,no,6,'18 and more',Self,NO
703,1,0,1,1,1,0,1,1,1,1,...,f,White-European,no,no,Cyprus,no,8,'18 and more',Self,YES

In [3]:
data_5['relation'].unique()

array(['Self', 'Parent', '?', "'Health care professional'", 'Relative',
       'Others'], dtype=object)

In [4]:
data_5['age'].unique()

array(['26', '24', '27', '35', '40', '36', '17', '64', '29', '33', '18',
       '31', '30', '34', '38', '42', '43', '48', '37', '55', '50', '53',
       '20', '28', '21', '383', '47', '32', '44', '?', '19', '58', '45',
       '22', '39', '25', '23', '54', '60', '41', '46', '56', '61', '59',
       '52', '49', '51'], dtype=object)

In [5]:
data_5['ethnicity'].unique()

array(['White-European', 'Latino', '?', 'Others', 'Black', 'Asian',
       "'Middle Eastern '", 'Pasifika', "'South Asian'", 'Hispanic',
       'Turkish', 'others'], dtype=object)

#### Converting binary categorial variable to numerical variables

In [6]:
data_5['gender'].replace(['f','m'], [0,1] ,inplace=True)
data_5['jundice'].replace(['no','yes'], [0,1] ,inplace=True)
data_5['austim'].replace(['no','yes'], [0,1] ,inplace=True)
data_5['used_app_before'].replace(['no','yes'], [0,1] ,inplace=True)
data_5['Class/ASD'].replace(['NO','YES'], [0,1] ,inplace=True)

In [7]:
data_5

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,...,0,White-European,0,0,'United States',0,6,'18 and more',Self,0
1,1,1,0,1,0,0,0,1,0,1,...,1,Latino,0,1,Brazil,0,5,'18 and more',Self,0
2,1,1,0,1,1,0,1,1,1,1,...,1,Latino,1,1,Spain,0,8,'18 and more',Parent,1
3,1,1,0,1,0,0,1,1,0,1,...,0,White-European,0,1,'United States',0,6,'18 and more',Self,0
4,1,0,0,0,0,0,0,1,0,0,...,0,?,0,0,Egypt,0,2,'18 and more',?,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,0,White-European,0,0,Russia,0,7,'18 and more',Self,1
700,1,0,0,0,0,0,0,1,0,1,...,1,Hispanic,0,0,Mexico,0,3,'18 and more',Parent,0
701,1,0,1,1,1,0,1,1,0,1,...,0,?,0,0,Russia,0,7,'18 and more',?,1
702,1,0,0,1,1,0,1,0,1,1,...,1,'South Asian',0,0,Pakistan,0,6,'18 and more',Self,0
703,1,0,1,1,1,0,1,1,1,1,...,0,White-European,0,0,Cyprus,0,8,'18 and more',Self,1

In [8]:
print("Counting ? values\n")
print(data_5.isin(['?']).sum(axis=0))

Counting ? values

A1_Score            0
A2_Score            0
A3_Score            0
A4_Score            0
A5_Score            0
A6_Score            0
A7_Score            0
A8_Score            0
A9_Score            0
A10_Score           0
age                 2
gender              0
ethnicity          95
jundice             0
austim              0
contry_of_res       0
used_app_before     0
result              0
age_desc            0
relation           95
Class/ASD           0
dtype: int64

#### Filling missing values

In [9]:
data_5["age"].mode()

0    21
dtype: object

In [10]:
data_5['relation'].mode()

0    Self
dtype: object

In [11]:
data_5['ethnicity'].mode()

0    White-European
dtype: object

In [12]:
data_5['ethnicity'] = data_5['ethnicity'].replace('?','White-European')
data_5['relation'] = data_5['relation'].replace('?','Self')
data_5['age'] = data_5['age'].replace('?','21')

In [13]:
data_5['relation'].unique()

array(['Self', 'Parent', "'Health care professional'", 'Relative',
       'Others'], dtype=object)

In [14]:
data_5['age'].unique()

array(['26', '24', '27', '35', '40', '36', '17', '64', '29', '33', '18',
       '31', '30', '34', '38', '42', '43', '48', '37', '55', '50', '53',
       '20', '28', '21', '383', '47', '32', '44', '19', '58', '45', '22',
       '39', '25', '23', '54', '60', '41', '46', '56', '61', '59', '52',
       '49', '51'], dtype=object)

In [15]:
data_5['ethnicity'].unique()

array(['White-European', 'Latino', 'Others', 'Black', 'Asian',
       "'Middle Eastern '", 'Pasifika', "'South Asian'", 'Hispanic',
       'Turkish', 'others'], dtype=object)

In [16]:
data_5.columns[data_5.isna().any()].tolist()

[]

In [17]:
print(data_5.isnull().any().any())
print(data_5.isnull().sum().sum())

False
0

#### DataFrame to CSV

In [18]:
data_5.to_csv('../DataSet/Screening/Screening question/new_Autism_Data.csv')